PKG_CHECK_MODULES(PC_GNURADIO_IIO gnuradio-iio)

FIND_PATH(
    GNURADIO_IIO_INCLUDE_DIRS
    NAMES gnuradio/iio/api.h
    HINTS $ENV{GNURADIO_IIO_DIR}/include
        ${PC_GNURADIO_IIO_INCLUDEDIR}
    PATHS /usr/local/include
          /usr/include
)

FIND_LIBRARY(
    GNURADIO_IIO_LIBRARIES
    NAME gnuradio-iio
    HINTS $ENV{GNURADIO_IIO_DIR}/lib
        ${PC_GNURADIO_IIO_LIBDIR}
    PATHS /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64
)

pkg_check_modules(PC_IIO libiio)

pkg_check_modules(PC_AD9361 libad9361)

# pkg_check_modules(PC_GR_IIO gnuradio-iio)

if (GNURADIO_IIO_INCLUDE_DIRS AND GNURADIO_IIO_LIBRARIES AND PC_IIO_FOUND AND PC_AD9361_FOUND)
    set(GR_IIO_FOUND TRUE CACHE INTERNAL "gnuradio-iio found")
    message(STATUS "Found gnuradio-iio: ${GNURADIO_IIO_INCLUDE_DIRS}, ${GNURADIO_IIO_LIBRARIES}")
else(GNURADIO_IIO_INCLUDE_DIRS AND GNURADIO_IIO_LIBRARIES AND PC_IIO_FOUND AND PC_AD9361_FOUND)
    set(GR_IIO_FOUND FALSE CACHE INTERNAL "gnuradio-uhd found")
endif(GNURADIO_IIO_INCLUDE_DIRS AND GNURADIO_IIO_LIBRARIES AND PC_IIO_FOUND AND PC_AD9361_FOUND)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(GnuradioIIO DEFAULT_MSG GNURADIO_IIO_LIBRARIES GNURADIO_IIO_INCLUDE_DIRS)
MARK_AS_ADVANCED(GNURADIO_IIO_LIBRARIES GNURADIO_IIO_INCLUDE_DIRS)
